project:
  type: website
  output-dir: _site
  resources:
    - _redirects

execute:
  freeze: auto

website:
  title: "Yulia Tyukhova"
  description: "Yulia Tyukhova is currently a Staff Software Engineer at NVIDIA, where she focuses on developing scalable evaluation systems for autonomous vehicles. Her passion, however, lies in LLMs, multimodal models, agentic AI, and frontier / foundation models in general."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications
        text: Publications
      - href: posts
        text: Blog
      - href: about.qmd
        text: About
  page-footer:
    left: "© Yulia Tyukhova, 2025 - [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  google-analytics: "G-DGMKGL1EBP"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
