project:
  type: website
  output-dir: _site
  resources:
    - _redirects

execute:
  freeze: auto

website:
  title: "Yulia Tyukhova"
  description: "Yulia Tyukhova is currently a Staff Software Engineer at NVIDIA, where she focuses on developing scalable evaluation systems for autonomous vehicles. Her passion, however, lies in LLMs, multimodal models, agentic AI, and frontier / foundation models in general."
  navbar:
    title: false
    logo: images/yt-logo-transparent.png
    left:
      - href: posts
        text: Hai-lights
      - href: services.qmd
        text: Services
      - text: About
        menu:
          - href: about/summary/
            text: Summary
          - href: about/publications/
            text: Publications
          - href: about/professional-organizations/
            text: Professional Organizations
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© Yulia Tyukhova, 2026 - [Disclaimer](disclaimer/) | [Terms Of Use](terms-of-use/)"
  twitter-card: true
  open-graph: true
  google-analytics: "G-DGMKGL1EBP"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
