---
title: "You are in on the hai-lights"
author: "Yulia Tyukhova"
date: "TBD"
categories: [news, introduction]
---

# You are in on the hai-lights

TBD

## Why I Started This Blog

The machine learning landscape is evolving at a breathtaking pace. From transformers to diffusion models, from reinforcement learning to neural radiance fields - there's an overwhelming amount of innovation happening. As someone navigating this field, I often find myself wanting to document my learning journey, break down complex ideas, and create resources I wish had existed when I was starting out.

This blog is my attempt to:

1. **Document my learning process** - Writing helps me solidify my understanding
2. **Develop and share practical tutorials** - With code examples that actually work. This is inspired by a few of the ML blogging greats: [Sebastian Raschka's blog](https://sebastianraschka.com/), [Andrej Karpathy's blog](https://karpathy.ai/), [Lilian Weng's blog](https://lilianweng.github.io/lil-log/), and many more.
3. **Summarize interesting papers** - Distilling key ideas from research into accessible explanations (in the spirit of [Two Minute Papers](https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg) but in longer written form). This is inspired by [Jay Alammar's Illustrated Transformer](https://jalammar.github.io/illustrated-transformer/) his [Illustrated Deep Seek R1](https://newsletter.languagemodels.co/p/the-illustrated-deepseek-r1) and overall his [Illustrated* series now available at Substack](https://newsletter.languagemodels.co/).
4. **Build in public** - Showing both successes and the inevitable struggles, and also post project walkthroughs.
5. **Link to resources** - Occasionally, I'll be posting links to useful resources - though I don't want to make this another newslettter or news aggregator.
